id: P40F62954
initial_creation_type: input
source_metadata:
  title: Udānavarga
  language: zh
  volumes:
    45beb50a64ce4bcca86c4626a512debf:
      title: CIII_Verses 1-10
      base_file: CIII_Verses 1-10.txt
      work_id: W11A54322
    86f17cf5126341449014e8ae301fb78c:
      title: CIII_Verses 11-18
      base_file: CIII_Verses 11-18.txt
      work_id: W28621CAD
    8609d08483bc45d38723e9dfc2dbc1f0:
      title: CII_Verses 1-10
      base_file: CII_Verses 1-10.txt
      work_id: W454499C0
    473c94c8013e4c33a6eac1868bfec48c:
      title: CII_Verses 11-20
      base_file: CII_Verses 11-20.txt
      work_id: WE7B5F2DF
    74368007a11d44008db2f0d124e05829:
      title: CIV_Verses 1-10
      base_file: CIV_Verses 1-10.txt
      work_id: W4C43734F
    70be8738387f421ab5a998e9d36d42bc:
      title: CIV_Verses 11-20
      base_file: CIV_Verses 11-20.txt
      work_id: W0BD1BDA0
    9f0844cdc940477880ce3a84583c080a:
      title: CIV_Verses 21-30
      base_file: CIV_Verses 21-30.txt
      work_id: WA9244BB0
    8a1e6c51e3cb4193a3685c3932c8219d:
      title: CIV_Verses 31-38
      base_file: CIV_Verses 31-38.txt
      work_id: W04333548
    b297d37d3af84bdaac7c33545805add6:
      title: CIX_Verses 1-10
      base_file: CIX_Verses 1-10.txt
      work_id: W6B597486
    5349608ca9014255ad603029d74d3c52:
      title: CIX_Verses 11-19
      base_file: CIX_Verses 11-19.txt
      work_id: WA2AAA605
    73a8b4e531104d2595d9655228a8e420:
      title: CI_Verses 1-10
      base_file: CI_Verses 1-10.txt
      work_id: WD383B094
    1f1ab43a74a24329b2bc526ba578a33c:
      title: CI_Verses 11-20
      base_file: CI_Verses 11-20.txt
      work_id: W4DED42D9
    c9248b11bd9f48f895df08cc9968c56d:
      title: CI_Verses 21-30
      base_file: CI_Verses 21-30.txt
      work_id: WAC84C9A4
    8776979666f84923895bfbd697dd3f63:
      title: CI_Verses 31-40
      base_file: CI_Verses 31-40.txt
      work_id: WE93CD9C9
    91bd5bea88f84483acd7bf9d733c9a52:
      title: CI_Verses 41-42
      base_file: CI_Verses 41-42.txt
      work_id: W75523D54
    44a72be89a0647a0aebfad85e9c69a96:
      title: CVIII_Verses 1-10
      base_file: CVIII_Verses 1-10.txt
      work_id: WED9E5824
    a541bd998e684c919c10c21f888243c6:
      title: CVIII_Verses 11-15
      base_file: CVIII_Verses 11-15.txt
      work_id: W5E7AB024
    60cd528df46e45b995e2b4dab95daaf2:
      title: CVII_Verses 1-10
      base_file: CVII_Verses 1-10.txt
      work_id: W015D6BDE
    7dedd7ec0a134f758219bf1af96e09d3:
      title: CVII_Verses 11-12
      base_file: CVII_Verses 11-12.txt
      work_id: W163F38F3
    9d7b1d76d8c04090b2e19ce72bbf65b8:
      title: CVI_Verses 1-10
      base_file: CVI_Verses 1-10.txt
      work_id: WE1343A48
    39cf742f3754488089b4b3cf1fa241c6:
      title: CVI_Verses 11-20
      base_file: CVI_Verses 11-20.txt
      work_id: W24C8F430
    a904a54e713e4c0aaaefc7379746e35b:
      title: CV_Verses 1-10
      base_file: CV_Verses 1-10.txt
      work_id: WAD1D3523
    0174fafabf4d4b98988bc9aae2dc0d7a:
      title: CV_Verses 11-20
      base_file: CV_Verses 11-20.txt
      work_id: W509033ED
    54186b0dcd0c409fb73ff85173434488:
      title: CV_Verses 21-27
      base_file: CV_Verses 21-27.txt
      work_id: W0AC9B0D3
    0e635d2569be4d57be83d2f9df900a55:
      title: CXIII_Verses 1-10
      base_file: CXIII_Verses 1-10.txt
      work_id: W81E7027B
    cf3e9404f9124da99880c0dd85363fd1:
      title: CXIII_Verses 11-18
      base_file: CXIII_Verses 11-18.txt
      work_id: WB682338B
    0b061029f47d452aa158cf4295516d3f:
      title: CXII_Verses 1-10
      base_file: CXII_Verses 1-10.txt
      work_id: WAAD271A4
    6a34b6d1d87f49c9ba49017da14fc025:
      title: CXII_Verses 11-20
      base_file: CXII_Verses 11-20.txt
      work_id: W7E000166
    164aee6c93d248979790865b6ab07790:
      title: CXIV_Verses 1-10
      base_file: CXIV_Verses 1-10.txt
      work_id: WDD5490BA
    c09d0c84bcc0414aa1ce5e91106281e1:
      title: CXIV_Verses 11-16
      base_file: CXIV_Verses 11-16.txt
      work_id: W3200E29F
    f3482ce0e52f450989142734cabf67a2:
      title: CXIX_Verses 1-10
      base_file: CXIX_Verses 1-10.txt
      work_id: WF58EE92E
    1def6c1d26dc4e8baf4bc9713a757c9e:
      title: CXIX_Verses 11-14
      base_file: CXIX_Verses 11-14.txt
      work_id: W79F9A99E
    26f39872b7de4bd1a9cc63b9f3dbc429:
      title: CXI_Verses 1-10
      base_file: CXI_Verses 1-10.txt
      work_id: W0544A7B3
    d592499770474c768127b52a40e72018:
      title: CXI_Verses 11-15
      base_file: CXI_Verses 11-15.txt
      work_id: W330CA5F8
    820e8738575c4f379955410b66107509:
      title: CXVIII_Verses 1-10
      base_file: CXVIII_Verses 1-10.txt
      work_id: W05FBFBEB
    9a70dd3714374bec9dd08e1a168ce284:
      title: CXVIII_Verses 11-20
      base_file: CXVIII_Verses 11-20.txt
      work_id: W4B528468
    9fddc666ac9c413a9213f39cb2d21b23:
      title: CXVIII_Verses 21-21F
      base_file: CXVIII_Verses 21-21F.txt
      work_id: W543C41B8
    08ce781d09264f8c93454aa19991aee2:
      title: CXVII_Verses 1-10
      base_file: CXVII_Verses 1-10.txt
      work_id: WDD2FFA6D
    54284b59c01b44279150cea3f93e2f66:
      title: CXVII_Verses 11-12
      base_file: CXVII_Verses 11-12.txt
      work_id: WE3EBE6EE
    a684e7da50c349d4bae8cd095073d48a:
      title: CXVI_Verses 1-10
      base_file: CXVI_Verses 1-10.txt
      work_id: W7AD69AA9
    3a19381d1ad948e4acd6f63b22357ba1:
      title: CXVI_Verses 11-20
      base_file: CXVI_Verses 11-20.txt
      work_id: W4C221244
    1b0ddf81d6784bc99f7ec8d2e055ff24:
      title: CXVI_Verses 21-24
      base_file: CXVI_Verses 21-24.txt
      work_id: WD97D77C9
    36af8a9136a94891a4e7c56689bce4a7:
      title: CXV_Verses 1-10
      base_file: CXV_Verses 1-10.txt
      work_id: W8EF4764D
    96e36f17ae274edabd1a0f563a7eab2c:
      title: CXV_Verses 11-20
      base_file: CXV_Verses 11-20.txt
      work_id: W0C10B2EB
    62b2322c9c3b47058fed9c3e6713b799:
      title: CXV_Verses 21-26
      base_file: CXV_Verses 21-26.txt
      work_id: W393A1823
    738488b00a8e49bb814ee9aafe643c7a:
      title: CXXIII_Verses 1-10
      base_file: CXXIII_Verses 1-10.txt
      work_id: W8FF493C8
    e8ef6eeea8aa413e8fb50b73e6f88813:
      title: CXXIII_Verses 11-20
      base_file: CXXIII_Verses 11-20.txt
      work_id: W42998999
    26b605397087419dab41f90852cdf092:
      title: CXXIII_Verses 21-26
      base_file: CXXIII_Verses 21-26.txt
      work_id: W048A55A7
    3a751742901d4fa1a34513a2a764fccf:
      title: CXXII_Verses 1-10
      base_file: CXXII_Verses 1-10.txt
      work_id: WE7CA9B8F
    dcc1e7149726401c804bf9bf7335b92f:
      title: CXXII_Verses 11-19
      base_file: CXXII_Verses 11-19.txt
      work_id: W0D874A55
    1e8c8b6bb8434e3a90c595a7d1585fb3:
      title: CXXIV_Verses 1-10
      base_file: CXXIV_Verses 1-10.txt
      work_id: W78C4F58B
    8ed95f260f644f66b2602eed3fb0470d:
      title: CXXIV_Verses 11-20
      base_file: CXXIV_Verses 11-20.txt
      work_id: W8CDAC944
    2d7891ab37884e7cbcf8c5e7ddaf6507:
      title: CXXIV_Verses 21-30
      base_file: CXXIV_Verses 21-30.txt
      work_id: W4B44AE4A
    152d3322cc454dcbb1705870547297fd:
      title: CXXIX_Verses 1-10
      base_file: CXXIX_Verses 1-10.txt
      work_id: W82313A07
    6fd4830231f04ed78cb3804a16d1321e:
      title: CXXIX_Verses 11-20
      base_file: CXXIX_Verses 11-20.txt
      work_id: W62125EEC
    70b13f0917b040cb86f879f4263403e1:
      title: CXXIX_Verses 21-30
      base_file: CXXIX_Verses 21-30.txt
      work_id: W85CDCAAE
    ab2482b2097a4c12977f25561ef43d42:
      title: CXXIX_Verses 31-40
      base_file: CXXIX_Verses 31-40.txt
      work_id: WC06204A5
    56451685622a4556ad1451385d1545a0:
      title: CXXIX_Verses 41-50
      base_file: CXXIX_Verses 41-50.txt
      work_id: W3223B4DB
    9cbfc58e3254438f9a33ba4a90f697fd:
      title: CXXIX_Verses 51-57
      base_file: CXXIX_Verses 51-57.txt
      work_id: W9588A131
    22de2a6dfee042d4bd20a8bf8d3a73b7:
      title: CXXI_Verses 1-10
      base_file: CXXI_Verses 1-10.txt
      work_id: W4E5399AE
    93a5cdd8048e4c4b9d407dd74d1a7cee:
      title: CXXI_Verses 11-18
      base_file: CXXI_Verses 11-18.txt
      work_id: WE46DB4E9
    4895ba3e47ae4894bcf47da88abd796c:
      title: CXXVIII_Verses 1-10
      base_file: CXXVIII_Verses 1-10.txt
      work_id: WDECC937A
    29e8d8b7ba7d4fc3967496cfc24ea04b:
      title: CXXVIII_Verses 11-20
      base_file: CXXVIII_Verses 11-20.txt
      work_id: WCCB85EE6
    28997f6659244530914f7b7998d96530:
      title: CXXVIII_Verses 21-30
      base_file: CXXVIII_Verses 21-30.txt
      work_id: WA6048079
    a3b264d955d549f99005568454afc878:
      title: CXXVIII_Verses 31-40
      base_file: CXXVIII_Verses 31-40.txt
      work_id: W79219993
    a75544c189bf4cce9738c6f83c47061b:
      title: CXXVII_Verse 41
      base_file: CXXVII_Verse 41.txt
      work_id: WF1B3A111
    4a14c7690ab146c5b04d36f955f4ef14:
      title: CXXVII_Verses 1-10
      base_file: CXXVII_Verses 1-10.txt
      work_id: W4AAD3E4D
    10fbbcf8fe1a45c28182312f66b7cc24:
      title: CXXVII_Verses 11-20
      base_file: CXXVII_Verses 11-20.txt
      work_id: W4DA44807
    10f28ad3ca0147bfbf4073958cbee14a:
      title: CXXVII_Verses 21-30
      base_file: CXXVII_Verses 21-30.txt
      work_id: WFEAA0D07
    aa30cb40dcf840019bf63f40566011b0:
      title: CXXVII_Verses 31-40
      base_file: CXXVII_Verses 31-40.txt
      work_id: WDACE4BAC
    9a3e80293e2a429e9a434730d902a46f:
      title: CXXVI_Verse 31
      base_file: CXXVI_Verse 31.txt
      work_id: W1A530808
    f49cfc86c6f044fa9a861845b03258e0:
      title: CXXVI_Verses 1-10
      base_file: CXXVI_Verses 1-10.txt
      work_id: W459AFF1B
    2d04653e09cb4a6dbe93cd26c809d482:
      title: CXXVI_Verses 11-20
      base_file: CXXVI_Verses 11-20.txt
      work_id: W62664243
    de140a428878443e9823aed114760f86:
      title: CXXVI_Verses 21-30
      base_file: CXXVI_Verses 21-30.txt
      work_id: W222CDA6E
    9411bc0df27343e3ba72529dc7603193:
      title: CXXV_Verses 1-10
      base_file: CXXV_Verses 1-10.txt
      work_id: W3E32C6C6
    eb193278cb0a49f982d17fb30ea37cea:
      title: CXXV_Verses 11-20
      base_file: CXXV_Verses 11-20.txt
      work_id: WA7573270
    a45a7e14a9b749149cac38ee59805e8f:
      title: CXXV_Verses 21-25
      base_file: CXXV_Verses 21-25.txt
      work_id: W945E90A8
    ef18262f77294b24ae44b3e2a166fb40:
      title: CXXXIII_Verses 1-10
      base_file: CXXXIII_Verses 1-10.txt
      work_id: W7D8B4DD5
    b5bda25e79c04d3bbfb3b373ab6bc561:
      title: CXXXIII_Verses 11-20
      base_file: CXXXIII_Verses 11-20.txt
      work_id: W5D381331
    c8b15dbd4aa7480cbe9fc37f60a91cbc:
      title: CXXXIII_Verses 21-30
      base_file: CXXXIII_Verses 21-30.txt
      work_id: W6948E644
    15ed90cac8d44f74b2a9fd66851bf16b:
      title: CXXXIII_Verses 31-40
      base_file: CXXXIII_Verses 31-40.txt
      work_id: WE58FD08B
    0da39e3e1d364249908af69de5377c20:
      title: CXXXIII_Verses 41-50
      base_file: CXXXIII_Verses 41-50.txt
      work_id: W5BD47EDD
    44c34f4de4c5460184893e1f4ce84c4c:
      title: CXXXIII_Verses 51-60
      base_file: CXXXIII_Verses 51-60.txt
      work_id: W38339402
    35ae494737324f1cb1e59272ce474a34:
      title: CXXXIII_Verses 61-70
      base_file: CXXXIII_Verses 61-70.txt
      work_id: W1C18C763
    532ba95a832b41d6aa8c8888d54c288f:
      title: CXXXIII_Verses 71-80
      base_file: CXXXIII_Verses 71-80.txt
      work_id: W1E18866A
    b6f8de82973e4d1db3f681ed8460b1b6:
      title: CXXXIII_Verses 81-83
      base_file: CXXXIII_Verses 81-83.txt
      work_id: WA2221B42
    fc5582cab27b41abba2e85c4abf93ab9:
      title: CXXXII_Verses 1-10
      base_file: CXXXII_Verses 1-10.txt
      work_id: W512CD84C
    d5cfef966cc642ef8f2241d130d896f4:
      title: CXXXII_Verses 11-20
      base_file: CXXXII_Verses 11-20.txt
      work_id: W305D7EF3
    aa40bddb67524d81ae9de178802c2a59:
      title: CXXXII_Verses 21-30
      base_file: CXXXII_Verses 21-30.txt
      work_id: WFA0FAD9A
    48b834b57b2c4d56a1bfe51b75c4b2a1:
      title: CXXXII_Verses 31-40
      base_file: CXXXII_Verses 31-40.txt
      work_id: W3243FD4E
    b4b46e1d3bf541b399dbe89b330ef273:
      title: CXXXII_Verses 41-50
      base_file: CXXXII_Verses 41-50.txt
      work_id: W992BA294
    61dd855d70ea41ba9a11c565aa3bcfb6:
      title: CXXXII_Verses 51-60
      base_file: CXXXII_Verses 51-60.txt
      work_id: WA0A44104
    e9f3b23502b34ad980e1d67eb4cc2399:
      title: CXXXII_Verses 61-70
      base_file: CXXXII_Verses 61-70.txt
      work_id: W5DB871BB
    8e61a74694f84c1c81b61bb001313220:
      title: CXXXII_Verses 71-80
      base_file: CXXXII_Verses 71-80.txt
      work_id: W993C4E81
    e61a74e28c8b4dddb680742b860b4c22:
      title: CXXXII_Verses 81-82
      base_file: CXXXII_Verses 81-82.txt
      work_id: W4EAC37BE
    405d027b646c419691e77bcc25784bb3:
      title: CXXXI_Verses 1-10
      base_file: CXXXI_Verses 1-10.txt
      work_id: WA764AFAF
    8406ca0a82694ee3982194d7aafdf9ad:
      title: CXXXI_Verses 11-20
      base_file: CXXXI_Verses 11-20.txt
      work_id: WD6F12CE0
    b0551fb1f70c4203be750702be8082b2:
      title: CXXXI_Verses 21-30
      base_file: CXXXI_Verses 21-30.txt
      work_id: W2A02C096
    ef1d323dc1a04d03bee7486b8f613dd8:
      title: CXXXI_Verses 31-40
      base_file: CXXXI_Verses 31-40.txt
      work_id: WBFD07E35
    accd14124a3f4fd2b1bedbec8e2d740f:
      title: CXXXI_Verses 41-50
      base_file: CXXXI_Verses 41-50.txt
      work_id: W90D5D226
    869b7ec365d64417872e4f19179d84c0:
      title: CXXXI_Verses 51-60
      base_file: CXXXI_Verses 51-60.txt
      work_id: WD5223ECA
    7b117c1dd00348899af9a87d17a63d92:
      title: CXXX_Verses 1-10
      base_file: CXXX_Verses 1-10.txt
      work_id: W32DC0C19
    f615cf2e94024015bef5d16da76916f2:
      title: CXXX_Verses 11-20
      base_file: CXXX_Verses 11-20.txt
      work_id: W3BC06449
    66d2e8ce427e4734aaf149d354252091:
      title: CXXX_Verses 21-30
      base_file: CXXX_Verses 21-30.txt
      work_id: W5C1E051E
    317550a2944e421692c15f4589fde3f4:
      title: CXXX_Verses 31-40
      base_file: CXXX_Verses 31-40.txt
      work_id: WF1F01471
    d5a954135d504a44a0adced69e211312:
      title: CXXX_Verses 41-50
      base_file: CXXX_Verses 41-50.txt
      work_id: WC4CE41DC
    fb2921a216f249b085da63775d04cc3b:
      title: CXXX_Verses 51-52
      base_file: CXXX_Verses 51-52.txt
      work_id: W4B084892
    f54e5547586b43b296de3bf49c2cb28c:
      title: CXX_Verses 1-10
      base_file: CXX_Verses 1-10.txt
      work_id: W7E73AA7C
    b8ef00cb49d84c73a5d98573d19c2b76:
      title: CXX_Verses 11-20
      base_file: CXX_Verses 11-20.txt
      work_id: WC1CCA0B1
    8547f2eb1550447fb9130545c3b5253a:
      title: CXX_Verses 21-22
      base_file: CXX_Verses 21-22.txt
      work_id: W4A1B1AB9
    38ddc3bec12c4779897ea394fe30d015:
      title: CX_Verses 1-10
      base_file: CX_Verses 1-10.txt
      work_id: W109691AC
    09798725ca0c40cfbc679bd37494b862:
      title: CX_Verses 11-16
      base_file: CX_Verses 11-16.txt
      work_id: W69298381
    7772d8f7d07f4fbe89de54df75afab9c:
      title: Colophon
      base_file: Colophon.txt
      work_id: W5A5DF01F
    120ec22250b04a539368786c79e29296:
      title: Preface
      base_file: Preface.txt
      work_id: W83452AC3
    0890fbd5cf394eeea67595c91c9aa717:
      title: Title
      base_file: Title.txt
      work_id: WD28ADF46
  chapter_to_tile:
    CI: 'Chapter I: Anityavarga'
    CII: 'Chapter II: Kāmavarga'
    CIII: 'Chapter III: Tṛṣṇāvarga'
    CIV: 'Chapter IV: Apramādavarga'
    CV: 'Chapter V: Priyavarga'
    CVI: 'Chapter VI: Śīlavarga'
    CVII: 'Chapter VII: Sucaritavarga'
    CVIII: 'Chapter VIII: Vācavarga'
    CIX: 'Chapter IX: Karmavarga'
    CX: 'Chatper X: Śraddhāvarga'
    CXI: 'Chapter XI: Śramaṇavarga'
    CXII: 'Chapter XII: Mārgavarga'
    CXIII: 'Chapter XIII: Satkāravarga'
    CXIV: 'Chapter XIV: Drohavarga'
    CXV: 'Chapter XV: Smṛtivarga'
    CXVI: 'Chapter XVI: Prakīrṇakavarga'
    CXVII: 'Chapter XVII: Udakavarga'
    CXVIII: 'Chapter XXIII: Puṣpavarga'
    CXIX: 'Chapter XIX: Aśvavarga'
    CXX: 'Chapter XX: Krodhavarga'
    CXXI: 'Chapter XXI: Tathāgatavarga'
    CXXII: 'Chapter XXII: Śrutavarga'
    CXXIII: 'Chapter XXIII: Ātmavarga'
    CXXIV: 'Chapter XXIV: Peyālavarga'
    CXXV: 'Chapter XXV: Mitravarga'
    CXXVI: 'Chapter XXVI: Nirvāṇavarga'
    CXXVII: 'Chapter XXVII: Paśyavarga'
    CXXVIII: 'Chapter XXVIII: Pāpavarga'
    CXXIX: 'Chapter XXIX: Yugavarga'
    CXXX: 'Chapter XXX: Sukhavarga'
    CXXXI: 'Chapter XXXI: Cittavarga'
    CXXXII: 'Chapter XXXII: Bhikṣuvarga'
    CXXXIII: 'Chapter XXXIII: Brāhmaṇavarga'
created_at: '2022-03-01T23:21:09.578800'
last_modified_at: '2022-03-01T23:21:09.578809'
